In [1]:
import numpy as np
# sklearn tutorial 
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print('ok') 

ok


In [2]:
import pandas as pd
iris_data = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
print(iris_data.head(5))
print(iris_data.columns)


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [3]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
iris_data['species'] = LE.fit_transform(iris_data['species'])
X = np.array(iris_data) 
print(X[:5]) 

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [4]:
# iris.data chứa dữ liệu X 
print(iris.data.shape) # shape của X 
print(iris.target.shape) # shape của labels 
print(iris.data[:10])
print(iris.feature_names)
print(iris.target) # có 3 labels: 0, 1, 2
print(iris.target_names)

(150, 4)
(150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [5]:
from sklearn.model_selection import train_test_split 
X = iris.data
y = iris.target 
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


In [11]:
# phân loại với KKN
from sklearn.neighbors import KNeighborsClassifier
k = 5
knn = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
knn.fit(X_train,y_train) 
y_pred = knn.predict(X_test)
print('y_pred:\n',y_pred) 
print('y_true:\n',y_test) 

# tính accuracy 
acc_score = metrics.accuracy_score(y_pred,y_test) 
print('accuracy:\n',acc_score) 

y_pred:
 [2 0 2 2 2 1 2 0 0 2 0 0 0 1 2 0 1 0 0 2 0 2 1 0 0 0 0 0 0 2]
y_true:
 [2 0 2 2 2 1 1 0 0 2 0 0 0 1 2 0 1 0 0 2 0 2 1 0 0 0 0 0 0 2]
accuracy:
 0.9666666666666667


In [6]:
# ví dụ về sử dụng SVM 
from sklearn import svm 
svm_classifier = svm.SVC(kernel='linear',gamma=0.01, C=100.)
svm_classifier.fit(X_train,y_train)

SVC(C=100.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [7]:
y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n',y_pred_svm)
print('y_true:\n',y_test) 


predict:
 [2 0 2 2 2 1 2 0 0 1 0 0 0 1 2 0 1 0 0 2 0 2 1 0 0 0 0 0 0 2]
y_true:
 [2 0 2 2 2 1 1 0 0 2 0 0 0 1 2 0 1 0 0 2 0 2 1 0 0 0 0 0 0 2]


In [9]:
# tính accuracy
from sklearn import metrics 
acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test) 
print('accuracy:\n',acc_score_svm) 


accuracy:
 0.9333333333333333
